api_server: ${api_server}
api_port: ${api_port}
ca_cert_file: ${ca_cert_file}
admin_cert_file: ${admin_cert_file}
admin_key_file: ${admin_key_file}
operator_cert_file: ${operator_cert_file}
operator_key_file: ${operator_key_file}
user_cert_file: ${user_cert_file}
user_key_file: ${user_key_file}
