// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewProject struct {
	Name string `json:"name"`
	Code string `json:"code"`
}

type Project struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Code string `json:"code"`
}
